Add/wishlist APIs
abdlrhman08/Distributed-project-backend pull request #21
Opened 2024-05-02 21:52 UTC by zainmo11

2024-05-02 22:19 UTC, abdlrhman08 requested changes
متنساش تعدل الformatting بس في الاخر 
و الauthentication في كل view

2024-05-02 22:19 UTC, abdlrhman08 commented on stats/views.py
> +
مدام مش بنستعمل `create` ملهاش لازمة نستعمل generics خليها APIView عادي 

او حل تاني انك ت override create

2024-05-02 22:19 UTC, abdlrhman08 commented on stats/views.py
> +class RemoveAllProducts_Wl_View(generics.DestroyAPIView):
خليها ClearWishlistView بس

2024-05-02 22:19 UTC, abdlrhman08 commented on stats/views.py
> +        user = self.request
`user = self.request.user`
و الif condition هنا ملهاش لازمة اوي لان كدا كدا انت حاطت permission class فوق فكدا فكدا ياما هيرجع user ياما permission denied

2024-05-02 22:19 UTC, abdlrhman08 commented on stats/views.py
> +    serializer_class = CustomerSerializer
ضيف الpermission classes و الauthentication

2024-05-02 22:19 UTC, abdlrhman08 commented on stats/views.py
> +    serializer_class = CustomerSerializer
الauthentication ارجوك

2024-05-03 14:11 UTC, SamehOssama approved these changes

2024-05-03 14:13 UTC, merged